apiVersion: v2
name: stigatron
description: A Helm chart for Kubernetes
type: application
version: 0.1.17
appVersion: "1.16.0"
dependencies: 
- name: heimdall2
  version: "0.1.6"
  repository: "https://rancherfederal.github.io/carbide-charts"
  alias: heimdall
