apiVersion: v2
name: stigatron
description: A Helm chart for Kubernetes
type: application
version: 0.1.5
appVersion: "1.16.0"
dependencies: []
# - name: heimdall2
#   version: "0.1.0"
#   repository: "https://rancherfederal.github.io/carbide-charts"
