apiVersion: v2
name: stigatron
description: Rancher Government Stigatron Extension
icon: https://raw.githubusercontent.com/rancherfederal/carbide-docs/main/static/img/carbide-logo.svg
type: application
version: 0.1.41
appVersion: "0.1.1"
dependencies:
  - name: heimdall2
    version: "0.1.29"
    repository: "https://rancherfederal.github.io/carbide-charts"
    alias: heimdall2
