apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "heimdall.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "heimdall.fullname" . }}-fleet-role
  namespace: {{ .Values.heimdall.fleetNamespace }}
rules:
- apiGroups: [""]
  resources: ["secrets", "namespaces"]
  verbs: ["get", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "heimdall.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "heimdall.fullname" . }}-rb
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "heimdall.fullname" . }}-sa
roleRef:
  kind: Role
  name: {{ include "heimdall.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "heimdall.fullname" . }}-fleet-rb
  namespace: {{ .Values.heimdall.fleetNamespace }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "heimdall.fullname" . }}-sa
roleRef:
  kind: Role
  name: {{ include "heimdall.fullname" . }}-fleet-role
  apiGroup: rbac.authorization.k8s.io