apiVersion: cis.cattle.io/v1
kind: ClusterScanBenchmark
metadata:
  name: rke2-stig-1.28
  annotations:
    field.cattle.io/description: RKE2 1.28 STIG Profile
spec:
  clusterProvider: rke2
  customBenchmarkConfigMapName: rke2-stig-1.28
  customBenchmarkConfigMapNamespace: cis-operator-system
  minKubernetesVersion: "1.28.0"
  maxKubernetesVersion: "1.28.30"