---
# Rancher
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-offline-docs
  namespace: "{{ .Values.namespace }}"
  labels:
    app: rancher-offline-docs
spec:
  selector:
    matchLabels:
      app: rancher-offline-docs
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rancher-offline-docs
    spec:
      containers:
        - name: rancher-offline-docs
          image: {{ .Values.image.registry }}/{{ .Values.image.name }}/rancher-docs:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
---
# longhorn
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-offline-docs
  namespace: "{{ .Values.namespace }}"
  labels:
    app: longhorn-offline-docs
spec:
  selector:
    matchLabels:
      app: longhorn-offline-docs
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: longhorn-offline-docs
    spec:
      containers:
        - name: longhorn-offline-docs
          imagePullPolicy: Always
          image: {{ .Values.image.registry }}/{{ .Values.image.name }}/longhorn-docs:{{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: 80

---
# elemental
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elemental-offline-docs
  namespace: "{{ .Values.namespace }}"
  labels:
    app: elemental-offline-docs
spec:
  selector:
    matchLabels:
      app: elemental-offline-docs
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elemental-offline-docs
    spec:
      containers:
        - name: elemental-offline-docs
          imagePullPolicy: Always
          # image: {{ .Values.image.registry }}/{{ .Values.image.name }}/carbide-elemental-docs:{{ .Values.image.tag }}
          image: {{ .Values.image.registry }}/{{ .Values.image.name }}/elemental-docs:{{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: 80

---
# rke2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rke2-offline-docs
  namespace: "{{ .Values.namespace }}"
  labels:
    app: rke2-offline-docs
spec:
  selector:
    matchLabels:
      app: rke2-offline-docs
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rke2-offline-docs
    spec:
      containers:
        - name: rke2-offline-docs
          imagePullPolicy: Always
          image: {{ .Values.image.registry }}/{{ .Values.image.name }}/rke2-docs:{{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: 80

---
# k3s
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-offline-docs
  namespace: "{{ .Values.namespace }}"
  labels:
    app: k3s-offline-docs
spec:
  selector:
    matchLabels:
      app: k3s-offline-docs
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k3s-offline-docs
    spec:
      containers:
        - name: k3s-offline-docs
          imagePullPolicy: Always
          image: {{ .Values.image.registry }}/{{ .Values.image.name }}/k3s-docs:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80

---
# carbide
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbide-offline-docs
  namespace: "{{ .Values.namespace }}"
  labels:
    app: carbide-offline-docs
spec:
  selector:
    matchLabels:
      app: carbide-offline-docs
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: carbide-offline-docs
    spec:
      containers:
        - name: carbide-offline-docs
          imagePullPolicy: Always
          #image: "{{ .Values.registry }}docs-carbide:{{ .Values.image.tag }}"
          #image: "{{ .Values.registry }}docs-carbide:{{ .Values.image.tag }}"
          # image: {{ .Values.image.registry }}/{{ .Values.image.name }}/comingsoon:{{ .Values.image.tag }}
          image: {{ .Values.image.registry }}/{{ .Values.image.name }}/carbide-docs:{{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: 80

---
# kubewarden
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubewarden-offline-docs
  namespace: "{{ .Values.namespace }}"
  labels:
    app: kubewarden-offline-docs
spec:
  selector:
    matchLabels:
      app: kubewarden-offline-docs
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubewarden-offline-docs
    spec:
      containers:
        - name: kubewarden-offline-docs
          imagePullPolicy: Always
          #image: "{{ .Values.registry }}docs-carbide:{{ .Values.image.tag }}"
          #image: "{{ .Values.registry }}docs-carbide:{{ .Values.image.tag }}"
          image: {{ .Values.image.registry }}/{{ .Values.image.name }}/kubewarden-docs:{{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: 80

---
# fleet
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-offline-docs
  namespace: "{{ .Values.namespace }}"
  labels:
    app: fleet-offline-docs
spec:
  selector:
    matchLabels:
      app: fleet-offline-docs
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fleet-offline-docs
    spec:
      containers:
        - name: fleet-offline-docs
          imagePullPolicy: Always
          #image: "{{ .Values.registry }}docs-carbide:{{ .Values.image.tag }}"
          #image: "{{ .Values.registry }}docs-carbide:{{ .Values.image.tag }}"
          image: {{ .Values.image.registry }}/{{ .Values.image.name }}/fleet-docs:{{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: 80

---
# neuvector
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuvector-offline-docs
  namespace: "{{ .Values.namespace }}"
  labels:
    app: neuvector-offline-docs
spec:
  selector:
    matchLabels:
      app: neuvector-offline-docs
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: neuvector-offline-docs
    spec:
      containers:
        - name: neuvector-offline-docs
          imagePullPolicy: Always
          # image: {{ .Values.image.registry }}/{{ .Values.image.name }}/comingsoon:{{ .Values.image.tag }}
          # image: bgulla/nv:latest
          image: {{ .Values.image.registry }}/{{ .Values.image.name }}/neuvector-docs:{{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: 80

---
# harvester
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harvester-offline-docs
  namespace: "{{ .Values.namespace }}"
  labels:
    app: harvester-offline-docs
spec:
  selector:
    matchLabels:
      app: harvester-offline-docs
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: harvester-offline-docs
    spec:
      containers:
        - name: harvester-offline-docs
          imagePullPolicy: Always
          image: {{ .Values.image.registry }}/{{ .Values.image.name }}/harvester-docs:{{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: 80

---
# cncf
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-offline-docs
  namespace: "{{ .Values.namespace }}"
  labels:
    app: kubernetes-offline-docs
spec:
  selector:
    matchLabels:
      app: kubernetes-offline-docs
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubernetes-offline-docs
    spec:
      containers:
        - name: kubernetes-offline-docs
          imagePullPolicy: Always
          image: {{ .Values.image.registry }}/{{ .Values.image.name }}/kubernetes-cncf-docs:{{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: 80
