apiVersion: v1
kind: ConfigMap
metadata:
  name: rke2-stig-1.25-preview
  namespace: cis-operator-system
data:
  config.yaml: |-
    ---
    master:
      components:
        - apiserver
        - scheduler
        - controllermanager
        - etcd
        - flanneld
        - kubernetes
        - kubelet
        - psa

      kubernetes:
        confs:
          - /etc/rancher/rke2/config.yaml
        defaultconf: /etc/rancher/rke2/config.yaml

      apiserver:
        bins:
          - "kube-apiserver"
          - "hyperkube apiserver"
          - "hyperkube kube-apiserver"
          - "apiserver"
          - "containerd"
        confs:
          - /etc/kubernetes/manifests/kube-apiserver.yaml
          - /etc/kubernetes/manifests/kube-apiserver.manifest
          - /var/snap/kube-apiserver/current/args
          - /var/lib/rancher/rke2/agent/pod-manifests/kube-apiserver.yaml
        defaultconf: /etc/kubernetes/manifests/kube-apiserver.yaml

      psa:
        bins: []
        confs:
          - /etc/rancher/rke2/rke2-pss.yaml
        defaultconf: /etc/rancher/rke2/rke2-pss.yaml

      scheduler:
        bins:
          - "kube-scheduler"
          - "hyperkube scheduler"
          - "hyperkube kube-scheduler"
          - "scheduler"
          - "containerd"
        confs:
          - /etc/kubernetes/manifests/kube-scheduler.yaml
          - /etc/kubernetes/manifests/kube-scheduler.manifest
          - /var/snap/kube-scheduler/current/args
          - /var/lib/rancher/rke2/agent/pod-manifests/kube-scheduler.yaml
        defaultconf: /etc/kubernetes/manifests/kube-scheduler.yaml

      controllermanager:
        bins:
          - "kube-controller-manager"
          - "kube-controller"
          - "hyperkube controller-manager"
          - "hyperkube kube-controller-manager"
          - "controller-manager"
          - "containerd"
        confs:
          - /etc/kubernetes/manifests/kube-controller-manager.yaml
          - /etc/kubernetes/manifests/kube-controller-manager.manifest
          - /var/snap/kube-controller-manager/current/args
          - /var/lib/rancher/rke2/agent/pod-manifests/kube-controller-manager.yaml
        defaultconf: /etc/kubernetes/manifests/kube-controller-manager.yaml

      etcd:
        optional: true
        bins:
          - "etcd"
        confs:
          - /etc/kubernetes/manifests/etcd.yaml
          - /etc/kubernetes/manifests/etcd.manifest
          - /etc/etcd/etcd.conf
          - /var/snap/etcd/common/etcd.conf.yml
          - /var/lib/rancher/rke2/server/db/etcd/config
        defaultconf: /etc/kubernetes/manifests/etcd.yaml

      flanneld:
        optional: true
        bins:
          - flanneld
        defaultconf: /etc/sysconfig/flanneld

      kubelet:
        bins:
          - "kubelet"
          - "hyperkube kubelet"

    node:
      components:
        - kubelet
        - proxy
        # kubernetes is a component to cover the config file /etc/kubernetes/config that is referred to in the benchmark
        - kubernetes

      kubernetes:
        defaultconf: "/etc/kubernetes/config"

      kubelet:
        cafile:
          - "/etc/kubernetes/pki/ca.crt"
          - "/etc/kubernetes/certs/ca.crt"
          - "/etc/kubernetes/cert/ca.pem"
          - "/etc/kubernetes/ssl/kube-ca.pem"
          - "/var/lib/rancher/rke2/agent/server.crt"
          - "/var/lib/rancher/rke2/agent/client-ca.crt"
          - "/var/lib/rancher/k3s/agent/client-ca.crt"
        svc:
          # These paths must also be included
          #  in the 'confs' property below
          - "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
          - "/etc/systemd/system/kubelet.service"
          - "/lib/systemd/system/kubelet.service"
          - "/etc/systemd/system/snap.kubelet.daemon.service"
        bins:
          - "kubelet"
          - "hyperkube kubelet"
          - "containerd"
        kubeconfig:
          - "/etc/kubernetes/kubelet.conf"
          - "/var/lib/kubelet/kubeconfig"
          - "/etc/kubernetes/kubelet-kubeconfig"
          - "/etc/kubernetes/ssl/kubecfg-kube-node.yaml"
          - "/var/lib/rancher/rke2/agent/kubelet.kubeconfig"
          - "/var/lib/rancher/k3s/server/cred/admin.kubeconfig"
          - "/var/lib/rancher/k3s/agent/kubelet.kubeconfig"
        confs:
          - "/var/lib/kubelet/config.yaml"
          - "/etc/kubernetes/kubelet/kubelet-config.json"
          - "/home/kubernetes/kubelet-config.yaml"
          - "/etc/default/kubelet"
          - "/var/lib/kubelet/kubeconfig"
          - "/var/snap/kubelet/current/args"
          ## Due to the fact that the kubelet might be configured
          ## without a kubelet-config file, we use a work-around
          ## of pointing to the systemd service file (which can also
          ## hold kubelet configuration).
          ## Note: The following paths must match the one under 'svc'
          - "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
          - "/etc/systemd/system/kubelet.service"
          - "/lib/systemd/system/kubelet.service"
          - "/etc/systemd/system/snap.kubelet.daemon.service"
          - "/etc/rancher/rke2/rke2.yaml"
          - /var/lib/rancher/rke2/agent/kubelet.kubeconfig
        defaultconf: "/var/lib/kubelet/config.yaml"
        defaultsvc: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
        defaultkubeconfig: "/etc/kubernetes/kubelet.conf"
        defaultcafile: "/etc/kubernetes/pki/ca.crt"

      proxy:
        optional: true
        bins:
          - "kube-proxy"
          - "hyperkube proxy"
          - "hyperkube kube-proxy"
          - "proxy"
          - "containerd"
        confs:
          - /etc/kubernetes/proxy
          - /etc/kubernetes/addons/kube-proxy-daemonset.yaml
          - /var/snap/kube-proxy/current/args
        kubeconfig:
          - /etc/kubernetes/kubelet-kubeconfig
          - /etc/kubernetes/ssl/kubecfg-kube-proxy.yaml
          - /var/lib/rancher/rke2/agent/kubeproxy.kubeconfig
          - /var/lib/rancher/k3s/agent/kubeproxy.kubeconfig
        svc:
          - "/lib/systemd/system/kube-proxy.service"
        defaultconf: /etc/kubernetes/addons/kube-proxy-daemonset.yaml
        defaultkubeconfig: "/etc/kubernetes/proxy.conf"

    etcd:
      components:
        - etcd

      etcd:
        bins:
          - "etcd"
          - "containerd"
        confs:
          - /etc/kubernetes/manifests/etcd.yaml
          - /etc/kubernetes/manifests/etcd.manifest
          - /etc/etcd/etcd.conf
          - /var/snap/etcd/common/etcd.conf.yml
          - /var/lib/rancher/rke2/agent/pod-manifests/etcd.yaml
          - /var/lib/rancher/k3s/server/db/etcd/config
        defaultconf: /etc/kubernetes/manifests/etcd.yaml

    version_mapping:
      "v1.25.0+rke2r1": "rke2-stig-1.25-preview"

    target_mapping:
      "rke2-stig-1.25-preview":
        - "node"
        - "etcd"
        - "master"
  etcd.yaml: |-
    ---
    controls:
    version: "rke2-profile"
    id: 10
    text: ""
    type: "etcd"
    groups: []
  master.yaml: |-
    controls:
    version: "rancher-profile"
    id: 1
    text: ""
    type: "master"
    groups:
    - id: V-254553
      text: ""
      checks:
      - id: V-254553-TLS-apiserver
        text: ""
        audit: "/bin/ps -fC $apiserverbin"
        tests:
          test_items:
          - flag: --tls-min-version
            compare:
              op: valid_elements
              value: VersionTLS12
            set: true
        remediation: ""
        scored: true
      - id: V-254553-TLS-controller
        text: ""
        audit: "/bin/ps -fC $controllermanagerbin"
        tests:
          test_items:
          - flag: --tls-min-version
            compare:
              op: valid_elements
              value: VersionTLS12
            set: true
        remediation: ""
        scored: true
      - id: V-254553-TLS-scheduler
        text: ""
        audit: "/bin/ps -fC $schedulerbin"
        tests:
          test_items:
          - flag: --tls-min-version
            compare:
              op: valid_elements
              value: VersionTLS12
            set: true
        remediation: ""
        scored: true
      - id: V-254553-Cipher-apiserver
        text: ""
        audit: "/bin/ps -fC $apiserverbin"
        tests:
          test_items:
          - flag: --tls-cipher-suites
            compare:
              op: valid_elements
              value: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256
            set: true
        remediation: ""
        scored: true
      - id: V-254553-Cipher-controller
        text: ""
        audit: "/bin/ps -fC $controllermanagerbin"
        tests:
          test_items:
          - flag: --tls-cipher-suites
            compare:
              op: valid_elements
              value: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256
            set: true
        remediation: ""
        scored: true
      - id: V-254553-Cipher-scheduler
        text: ""
        audit: "/bin/ps -fC $schedulerbin"
        tests:
          test_items:
          - flag: --tls-cipher-suites
            compare:
              op: valid_elements
              value: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256
            set: true
        remediation: ""
        scored: true

    - id: "V-254554"
      text: ""
      checks:
      - id: V-254554
        text: ""
        audit: "/bin/ps -fC $controllermanagerbin"
        tests:
          test_items:
          - flag: --use-service-account-credentials
            compare:
              op: eq
              value: true
            set: true
        remediation: ""
        scored: true
    - id: "V-254555"
      text: ""
      checks:
      - id: V-254555
        text: ""
        audit: "/bin/ps -fC $apiserverbin"
        tests:
          bin_op: and
          test_items:
          - flag: --audit-policy-file
            compare:
              op: eq
              value: "/etc/rancher/rke2/audit-policy.yaml"
            set: true
          - flag: --audit-log-mode
            compare:
              op: eq
              value: blocking-strict
            set: true
        remediation: ""
        scored: true
    - id: "V-254556"
      text: ""
      checks:
      - id: V-254556
        text: ""
        audit: "/bin/ps -fC $controllermanagerbin"
        tests:
          test_items:
          - flag: --bind-address
            compare:
              op: eq
              value: "127.0.0.1"
            set: true
        remediation: ""
        scored: true
    - id: "V-254557"
      text: ""
      checks:
      - id: V-254557
        text: ""
        audit: "/bin/ps -fC $kubeletbin"
        tests:
          test_items:
          - flag: --anonymous-auth
            compare:
              op: eq
              value: false
            set: true
        remediation: ""
        scored: true
    - id: "V-254558"
      text: ""
      checks:
      - id: V-254558
        text: ""
        audit: "/bin/ps -fC $apiserverbin"
        tests:
          test_items:
          - flag: --insecure-port
            set: false
        remediation: ""
        scored: true
    - id: "V-254559"
      text: ""
      checks:
      - id: V-254559
        text: ""
        audit: "/bin/ps -fC $kubeletbin"
        tests:
          test_items:
          - flag: --read-only-port
            compare:
              op: eq
              value: "0"
            set: true
        remediation: ""
        scored: true
      #Need to fix
    - id: "V-254560"
      text: ""
      checks:
      - id: V-254560
        text: ""
        audit: "/bin/ps -fC $apiserverbin"
        tests:
          test_items:
          - flag: --insecure-bind-address
            set: false
        remediation: ""
        scored: true
    - id: "V-254561"
      text: ""
      checks:
      - id: V-254561
        text: ""
        audit: "/bin/ps -fC $kubeletbin"
        tests:
          test_items:
          - flag: --authorization-mode
            compare:
              op: eq
              value: "Webhook"
            set: true
        remediation: ""
        scored: true
    - id: "V-254562"
      text: ""
      checks:
      - id: V-254562
        text: ""
        audit: "/bin/ps -fC $apiserverbin"
        tests:
          test_items:
          - flag: --anonymous-auth
            compare:
              op: eq
              value: false
            set: true
        remediation: ""
        scored: true
    - id: "V-254563"
      text: ""
      checks:
      - id: V-254563
        text: ""
        audit: "/bin/ps -fC $apiserverbin"
        tests:
          test_items:
          - flag: --audit-log-maxage
            compare:
              op: gte
              value: 30
            set: true
        remediation: ""
        scored: true

    # MANUAL
    - id: "V-254564"
      text: ""
      checks:
      - id: V-254564
        text: ""
        type: "skip"
        remediation: ""

    # MANUAL
    - id: "V-254565"
      text: ""
      checks:
      - id: V-254565
        text: ""
        type: "skip"
        remediation: ""

    # MANUAL
    - id: "V-254566"
      text: ""
      checks:
      - id: V-254566
        text: ""
        type: "skip"
        remediation: ""

    # MANUAL
    - id: "V-254567"
      text: ""
      checks:
      - id: V-254567
        text: ""
        type: "skip"
        remediation: ""
    - id: "V-254568"
      text: ""
      checks:
      - id: V-254568
        text: ""
        audit: "/bin/ps -fC $kubeletbin"
        tests:
          test_items:
          - flag: --streaming-connection-idle-timeout
            compare:
              op: eq
              value: "5m"
            set: true
        remediation: ""
        scored: true

    - id: "V-254569"
      text: ""
      checks:
      - id: V-254569
        text: ""
        audit: "/bin/ps -fC $kubeletbin"
        tests:
          test_items:
          - flag: --protect-kernel-defaults
            compare:
              op: eq
              value: true
            set: true
        remediation: ""
        scored: true

    # MANUAL
    - id: "V-254570"
      text: ""
      checks:
      - id: V-254570
        text: ""
        type: "skip"
        remediation: ""

    - id: "V-254571"
      text: ""
      checks:
      - id: V-254571
        text: ""
        audit: "/bin/cat $psaconf"
        tests:
          bin_op: and
          test_items:
            - path: '{.plugins[0].defaults.enforce}'
              compare:
                op: eq
                value: "restricted"
            - path: '{.plugins[0].defaults.enforce-version}'
              compare:
                op: eq
                value: "latest"
              
            - path: '{.plugins[0].defaults.audit}'
              compare:
                op: eq
                value: "restricted"
            - path: '{.plugins[0].defaults.audit-version}'
              compare:
                op: eq
                value: "latest"

            - path: '{.plugins[0].defaults.warn}'
              compare:
                op: eq
                value: "restricted"
            - path: '{.plugins[0].defaults.warn-version}'
              compare:
                op: eq
                value: "latest"
        remediation: ""
        scored: true

    - id: "V-254572"
      text: ""
      checks:
      - id: V-254572
        text: ""
        audit: "/bin/ps -fC $apiserverbin"
        tests:
          test_items:
          - flag: --authorization-mode
            compare:
              op: eq
              value: "RBAC,Node"
            set: true
        remediation: ""
        scored: true

    - id: "V-254573"
      text: ""
      checks:
      - id: V-254573
        text: ""
        audit_config: "/bin/cat $kubernetesconf"
        tests:
          bin_op: or
          test_items:
            - path: '{.secrets-encryption}'
              compare:
                op: eq
                value: true
            - path: '{.secrets-encryption}'
              set: false
        remediation: ""
        scored: true

    # MANUAL
    - id: "V-254574"
      text: ""
      checks:
      - id: V-254574
        text: ""
        type: "skip"
        remediation: ""

    # MANUAL
    - id: "V-254575"
      text: ""
      checks:
      - id: V-254575
        text: ""
        type: "skip"
        remediation: ""
  node.yaml: |-
    ---
    controls:
    version: "rke2-profile"
    id: 12
    text: ""
    type: "node"
    groups: []
