apiVersion: v2
name: stigatron-ui
description: Rancher Government Stigatron UI Extension
icon: https://raw.githubusercontent.com/rancherfederal/carbide-docs/main/static/img/carbide-logo.svg
type: application
version: 0.1.22
appVersion: "0.1.1"
