apiVersion: v1
kind: ServiceAccount
metadata:
  name: branding-prehook
  namespace: kube-system
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": hook-failed,hook-succeeded
    "helm.sh/hook-weight": "-10"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: branding-prehook
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": hook-failed,hook-succeeded
    "helm.sh/hook-weight": "-10"
  labels:
    rbac.example.com/aggregate-to-monitoring: "true"
rules:
- apiGroups: ["settings","management.cattle.io","settings.management.cattle.io"]
  resources: ["settings", "settings.management.cattle.io"] # TODO: lock this down
  verbs: ["get", "list", "watch", "annotate", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: branding-prehook
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": hook-failed,hook-succeeded
    "helm.sh/hook-weight": "-10"
subjects:
  - kind: ServiceAccount
    name: branding-prehook
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: branding-prehook
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: annotate-ui-setting
  namespace: kube-system
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  containers:
  - name: itstimefortheannotate
    image: rancher/hyperkube:v1.23.16-rancher1
    command:
    - kubectl
    - annotate
    - settings.management.cattle.io
    - ui-favicon
    - "app.kubernetes.io/managed-by=Helm"
    - "meta.helm.sh/release-name=docs"
    - "meta.helm.sh/release-namespace=carbide-system"
  - name: labeler
    image: rancher/hyperkube:v1.23.16-rancher1
    command:
    - kubectl
    - label
    - settings.management.cattle.io
    - ui-favicon
    - "app.kubernetes.io/managed-by=Helm"
    - "meta.helm.sh/release-name=docs"
    - "meta.helm.sh/release-namespace=carbide-system"
  restartPolicy: Never
  serviceAccountName: branding-prehook