apiVersion: cis.cattle.io/v1
kind: ClusterScanBenchmark
metadata:
  name: rke2-stig-1.29-preview
  annotations:
    field.cattle.io/description: RKE2 1.29 STIG Profile
spec:
  clusterProvider: rke2
  customBenchmarkConfigMapName: rke2-stig-1.29-preview
  customBenchmarkConfigMapNamespace: cis-operator-system
  minKubernetesVersion: "1.29.0"
  maxKubernetesVersion: "1.29.30"