apiVersion: v2
name: airgapped-docs
version: 0.1.55
appVersion: 0.1.8

type: application
description: Rancher Government Airgapped Docs
icon: https://raw.githubusercontent.com/rancherfederal/carbide-docs/main/static/img/carbide-logo.svg

annotations:
  classification: UNCLASSIFIED
