apiVersion: v2
name: airgapped-docs
description: Rancher Government Airgapped Docs
icon: https://raw.githubusercontent.com/rancherfederal/carbide-docs/main/static/img/carbide-logo.svg
type: application
version: 0.1.53
appVersion: "0.1.7"
